#!/bin/sh
set -e

# deps
DEPS="lib32gcc1"
DEPS_BUILD="wget ca-certificates"

# install deps
apt-get update
apt-get install -y $DEPS $DEPS_BUILD

# download & install steamcmd
mkdir -p /opt/steamcmd
cd /opt/steamcmd
wget -qO- "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" \
	| tar -xz --no-same-owner --no-same-permissions

chmod 555 /opt/steamcmd/* -R

# update steamcmd
./steamcmd.sh +quit

# add a "steam" user and group
adduser --system --group steam

# set owner and group to "steam"
chown steam:steam -R /opt/steamcmd

# clean up
apt-get purge -y $DEPS_BUILD
apt-get autoremove -y
apt-get clean
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
